### ISSUE TITLE
Constant console/log spam on 1.34.2

### ISSUE THREAD

**Issue by TheBlackParrot** [Sirspam/MenuPillars#3]
Tried the version for 1.31 in 1.34.2 since I wanted to get around to updating the game from 1.29.1, and MenuPillars constantly spams something about a color function upon the mod loading.
[2024.05.28.04.12.14.log](https://github.com/Sirspam/MenuPillars/files/15466921/2024.05.28.04.12.14.log)

**Comment by Taffeeko** [comment]
I unfortunately don't have any plans for updating MenuPillars for 1.34 as I still personally use 1.29.1, I'll be updating it whenever I move to latest.
